### PR TITLE
Update template and pretranslate strings

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by jpmckinney** [comment]
OCDS for PPPs is being translated, so we can do another pre-translation once it's done.

**Comment by duncandewhurst** [comment]
I checked a few pages and the preview looks good. Is there anything in particular that I need to check in the changed files?

Do we need to wait until the OCDS for PPPs translation is done before asking CDS to start on translating OC4IDS?

The content on the Getting Started and CoST IDS and OCDS Mapping pages is entirely new and will have little to no cross-over with OCDS for PPPs, so I'm wondering if they can make a start on those pages at least?

**Comment by jpmckinney** [comment]
CDS can only really translate one project at a time, so I don't think there is any advantage to starting OC4IDS while still finishing PPPs.

**Comment by jpmckinney** [comment]
Merging to avoid conflicts. We can start a new PR for the next pretranslation and translation.

**Pull request merged**
