### PR TITLE
refer to OCDS docs for shared codelists

### LINKED ISSUE #145: Move OCDS codelists to the top of the codelist reference page
From @jpmckinney:

> please put the references at the top of the page, before the codelists. As a documentation user, I find that I assume the structure of the page is codelist names followed by tables; I wouldn't expect to look for or find a list of links at the bottom of the long page

### PR DESCRIPTION
**Pull request by duncandewhurst**
Closes #145 

Also, put OCDS codelists in alphabetical order

### CODE REVIEW

**Review by jpmckinney — COMMENTED** [review]
I think there are links in the schema to the OC4IDS codelists page for at least the method codelist.

**Comment by duncandewhurst** [comment]
I've updated the URL in the schema for the method codelist.

The currency codelist URL already pointed to the OCDS docs.

**Comment by duncandewhurst** [comment]
Ready for review and merging

**Comment by jpmckinney** [comment]
I added a commit with a couple copy-edits. We don't specify "OCDS <name> codelist" for any other codelists, so I restored it.

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
