### PR TITLE
Update build

### LINKED ISSUE #6: Typo: roles is repeated in Organization table
https://open-contracting.github.io/infrastructure/projects/reference/#organization

### LINKED ISSUE #26: Build process
I've updated and simplified the default build process for OCDS documentation. However, when trying to write a PR for this repo, I'm confused that requirements.in uses an unpinned version of Sphinx, and a version of recommonmark that is incompatible with the rest of our tooling. Is requirements.in in use, and if not can it be deleted?

The repository also omits Babel configuration files, which are required to support the translation of codelists and schema. I assume this omission isn't deliberate?

If my assumptions are correct, I'm happy to proceed with a PR.

### PR DESCRIPTION
**Pull request by jpmckinney**
closes #6, closes #26

### CODE REVIEW

**Comment by duncandewhurst** [comment]
I tested this on a fresh virtual environment and the build is failing on the `sphinx-build -q -b dirhtml docs build/en` command with TypeError: join() argument must be str or bytes, not 'PosixPath'

**Comment by jpmckinney** [comment]
I made a fresh environment, `pip install -r requirements.txt` and `make`, and I get this output:

```
if [ -n "" ]; then cp -r  build; fi
rm -f build/current_lang
rm -f build/codelists/current_lang
mkdir -p build/codelists
ln -s en build/current_lang
ln -s en build/codelists/current_lang
sphinx-build -q -b dirhtml docs build/en
/Users/james/Sites/remote/open-contracting/infrastructure/docs/about.md:32: WARNING: image file not readable: ../_static/images/OC-CoST-TheoryOfChange-June2018.png
/Users/james/Sites/remote/open-contracting/infrastructure/docs/cost/index.md:6: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/Users/james/Sites/remote/open-contracting/infrastructure/docs/cost/index.md:6: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/Users/james/Sites/remote/open-contracting/infrastructure/docs/projects/index.md:9: WARNING: image file not readable: projects/../../_static/images/diagram-project-contract.png
/Users/james/Sites/remote/open-contracting/infrastructure/docs/projects/index.md:15: WARNING: image file not readable: projects/../../_static/images/diagram-project-phases.png
/Users/james/Sites/remote/open-contracting/infrastructure/docs/projects/index.md:28: WARNING: image file not readable: projects/../../_static/images/diagram-project-contract-phases.png
/Users/james/Sites/remote/open-contracting/infrastructure/docs/projects/index.md:38: WARNING: image file not readable: projects/../../_static/images/diagram-project-level-data-spec.png
/Users/james/Sites/remote/open-contracting/infrastructure/docs/projects/reference.md:33: WARNING: Collapse values don't exist: {'releaseList'}
# pybabel compile --use-fuzzy -d locale -D infrastructureschema
# pybabel compile --use-fuzzy -d locale -D infrastructurecodelists
rm build/current_lang
rm build/codelists/current_lang
```

Can you share your entire output?

**Comment by jpmckinney** [comment]
Can you share the full traceback, saved in `/tmp/sphinx-err-5opsyd1d.log` according to the error message?

**Comment by duncandewhurst** [comment]
```
# Sphinx version: 1.5.1
# Python version: 3.5.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/ddewhurst/open_data_services/ocds/repositories/infrastructure-build-test/.ve/lib/python3.5/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/ddewhurst/open_data_services/ocds/repositories/infrastructure-build-test/.ve/lib/python3.5/site-packages/sphinx/application.py", line 205, in __init__
    self.config.setup(self)
  File "conf.py", line 174, in setup
  File "/home/ddewhurst/open_data_services/ocds/repositories/infrastructure-build-test/.ve/lib/python3.5/site-packages/ocds_babel/translate.py", line 39, in translate
    domain, localedir, languages=[language], fallback=language == 'en')
  File "/usr/lib/python3.5/gettext.py", line 428, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib/python3.5/gettext.py", line 396, in find
    mofile = os.path.join(localedir, lang, 'LC_MESSAGES', '%s.mo' % domain)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'
```

**Comment by jpmckinney** [comment]
Aha, you need Python 3.6 for this improvement: https://docs.python.org/3/whatsnew/3.6.html#pep-519-adding-a-file-system-path-protocol Is that an issue for you?

**Comment by duncandewhurst** [comment]
I tested with python 3.6 and the build completed successfully.

I've added a note on requiring python 3.6 to the build process in the standard dev handbook

We should think about how changes such as this as are communicated to people who might need to build the documentation

**Pull request merged**
