### PR TITLE
Updating wording from 0.9

### PR DESCRIPTION
**Pull request by odscrachel**
Updating support page to include email addresses for OCP and CoST. This is from 0.9 instead of 0.9-dev.

### CODE REVIEW

**Comment by duncandewhurst** [comment]
The `build` jobs in the CI and Lint actions are failing with the same error:

```
Run actions/setup-python@v1
Error: Version 3.6 with arch x64 not found
Available versions:

3.10.8 (x64)
3.11.0 (x64)
3.7.15 (x64)
3.8.15 (x64)
3.9.15 (x64)
```

I think this is because Python 3.6 is no longer supported on `ubuntu-latest`: https://github.com/actions/setup-python/issues/544#issuecomment-1332535877

There are two possible solutions:

1. Change `runs-on` in `ci.yml` and `lint.yml` from `ubuntu-latest` to `ubuntu-20.04`:

https://github.com/open-contracting/infrastructure/blob/787dca7d9d22594c3016aa53d0898410188918de/.github/workflows/ci.yml#L6

2. Change `python-version` in `ci.yml` and `lint.yml` from `3.6` to `3.7` or above:

https://github.com/open-contracting/infrastructure/blob/787dca7d9d22594c3016aa53d0898410188918de/.github/workflows/ci.yml#L13

@jpmckinney do you have a preference?

**Comment by jpmckinney** [comment]
I fixed this in 0.9 dev. I'll cherry-pick the appropriate commits.

**Comment by jpmckinney** [comment]
```
git log --oneline 0.9..0.9-dev -- .github/ | cut -f1 -d" "
```

Reverse the output in a text editor, to run:

```
git cherry-pick 1cf4080 298fcc9 a017337 295ff30 ccbc4ad ae825d1
```

----

Note that I tried to merge more build-only commits, but a few of these include changes outside build files, which became to complicated to handle.

```
git log --oneline 0.9..0.9-dev | grep -E ' build| include| ci| requirements| manage:| manage\.py:| \./manage\.py:| test:|512e910|17519f3|61cdcf0' | cut -f1 -d" " | grep -v 0d159bd
```

**Comment by jpmckinney** [comment]
Now also ran:

```
git cherry-pick b9e34d2 512e910 9016019
```

To get the necessary updates to `requirements.txt`. Note that I had to not merge the changes to changelog.md in b9e34d2

**Comment by jpmckinney** [comment]
And to fix lint errors I ran:

```
git cherry-pick 61cdcf0 17519f3
```

Again had to ignore changes to changelog.md in 61cdcf0

**Comment by jpmckinney** [comment]
It builds now 🚀

**Comment by duncandewhurst** [comment]
Awesome! Thanks for the Git wizardry :-)

**Review by duncandewhurst — APPROVED** [review]

**Comment by jpmckinney** [comment]
Automatically deployed: https://standard.open-contracting.org/infrastructure/latest/en/support/

**Comment by jpmckinney** [comment]
I've merged 0.9 into 0.9-dev to avoid future merge conflicts in https://github.com/open-contracting/infrastructure/commit/4e4549c9ba36439379e11630d4a0a446817361ad

**Pull request merged**
