### PR TITLE
correct references to document.type in mapping

### PR DESCRIPTION
**Pull request by duncandewhurst**
Replace references to `.type` with `.documentType`.

[Slack thread](https://opencontractingint.slack.com/archives/C01N5FPUWNM/p1621886319019700)

### CODE REVIEW

**Comment by duncandewhurst** [comment]
@jpmckinney the build is failing with an error related to myst-parser:

```
Run pip install --src $GITHUB_WORKSPACE/../src -r requirements.txt
Obtaining myst-parser from git+https://github.com/jpmckinney/MyST-Parser.git@heading_slug_func#egg=myst-parser (from -r common-requirements.txt (line 7))
  Running command git clone -q https://github.com/jpmckinney/MyST-Parser.git /home/runner/work/infrastructure/src/myst-parser
  Cloning https://github.com/jpmckinney/MyST-Parser.git (to revision heading_slug_func) to /home/runner/work/infrastructure/src/myst-parser
  WARNING: Did not find branch or tag 'heading_slug_func', assuming revision or ref.
  Running command git checkout -q heading_slug_func
  error: pathspec 'heading_slug_func' did not match any file(s) known to git
WARNING: Discarding git+https://github.com/jpmckinney/MyST-Parser.git@heading_slug_func#egg=myst-parser. Command errored out with exit status 1: git checkout -q heading_slug_func Check the logs for full command output.
Obtaining standard_theme from git+https://github.com/open-contracting/standard_theme.git@open_contracting#egg=standard_theme (from -r common-requirements.txt (line 9))
  Running command git clone -q https://github.com/open-contracting/standard_theme.git /home/runner/work/infrastructure/src/standard-theme
  Cloning https://github.com/open-contracting/standard_theme.git (to revision open_contracting) to /home/runner/work/infrastructure/src/standard-theme
Obtaining sphinxcontrib-opendataservices from git+https://github.com/jpmckinney/sphinxcontrib-opendataservices.git@tests#egg=sphinxcontrib-opendataservices (from -r requirements.txt (line 7))
  Running command git clone -q https://github.com/jpmckinney/sphinxcontrib-opendataservices.git /home/runner/work/infrastructure/src/sphinxcontrib-opendataservices
  Cloning https://github.com/jpmckinney/sphinxcontrib-opendataservices.git (to revision tests) to /home/runner/work/infrastructure/src/sphinxcontrib-opendataservices
  Running command git checkout -b tests --track origin/tests
  Switched to a new branch 'tests'
  Branch 'tests' set up to track remote branch 'tests' from 'origin'.
ERROR: Could not find a version that satisfies the requirement myst-parser (unavailable) (from versions: 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0a1, 0.5.0, 0.5.1, 0.6.0a1, 0.6.0a2, 0.6.0a3, 0.6.0, 0.7.0, 0.7.1, 0.8.0a1, 0.8.0a2, 0.8.0a3, 0.8.0a4, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.10, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0a1, 0.14.0a2, 0.14.0a3, 0.14.0)
ERROR: No matching distribution found for myst-parser (unavailable)
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.6.13/x64/bin/python -m pip install --upgrade pip' command.
Error: Process completed with exit code 1.
```

**Comment by jpmckinney** [comment]
@duncandewhurst It builds now.

**Comment by duncandewhurst** [comment]
Thanks!

**Review by jpmckinney — APPROVED** [review]
I haven't audited for other occurrences of `type`. I trust you found them all :)

**Comment by duncandewhurst** [comment]
`Modification` also has a `.type` field, so I changed all the occurrences that relate to `Document`!

**Pull request merged**
