### PR TITLE
Typos

### LINKED ISSUE #165: Spellcheck project
Further to spelling corrections in the schema #157 we should run a spellcheck across the whole project.

### PR DESCRIPTION
**Pull request by jpmckinney**
Closes #165.

This is likely to cause conflicts with other PRs, so it'd be good to merge before making new PRs.

### CODE REVIEW

**Comment by jpmckinney** [comment]
These are mostly British->American spelling, but there are a few transpositions of adjacent characters (proflie), lowercase proper nouns (saxon), missing characters (administativeEntity), and other typos.

**Comment by jpmckinney** [comment]
On the other hand, we might want to review and merge the others first. I can do this quickly now that I've done it once (I know where all the typos are).

**Comment by duncandewhurst** [comment]
Thanks @jpmckinney I think it will be easier to merge the others first, then review and then re-run the spell check, if that is not too much work

**Comment by jpmckinney** [comment]
Makes sense to me. I'll close this so that I don't merge it accidentally!

**Pull request closed without merging**
